name: Makefile CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

  

    - name: Install dependencies
      run: make

    - name: Run test
      run: make test

 
